@BO.Apis_HostAddress = http://localhost:5179

### create source connector

POST {{BO.Apis_HostAddress }}/connectors/sources/postgresql
content-type: application/json

{
  "name": "test",
  "connectionString": "Host=localhost:5432;Database=grouparoo_docker;Username=postgres;Password=password",
  "schema": "northwind",
  "tables": "categories,customers,orders,order_details",
  "kafkaServer": "localhost:29092"
}

### create source connector

POST {{BO.Apis_HostAddress }}/connectors/destinations/postgresql
content-type: application/json

{
  "name": "northwind_replication",
  "topicPattern": "bo_connector_northwind_.*",
  "connectionString": "Host=localhost:5432;Database=grouparoo_docker;Username=postgres;Password=password",
  "schema": "northwind_replication",
  "kafkaServer": "localhost:29092"
}