<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Paillave.EtlNet.Core" Version="2.0.47" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shares\BO.Core\BO.Core.csproj" />
    <ProjectReference Include="..\..\Shares\Bo.Kafka\Bo.Kafka.csproj" />
  </ItemGroup>

</Project>
